### PR TITLE
labelmaker: Add layout for UW Reopening barcodes

### PR DESCRIPTION
**Pull request by kairstenfay**
Add two new layouts for the UW Reopening (a.k.a. Husky Coronavirus
Testing) study collection barcode sets.

- [ ] Update Barcodes documentation

### CODE REVIEW

**Comment by kairstenfay** [comment]
[Create labelmaker layout for UW reopening barcodes](https://trello.com/c/4wOwUjLg/774-create-labelmaker-layout-for-uw-reopening-barcodes)

**Review by joverlee521 — CHANGES_REQUESTED** [review]
I think the reference should still be `seattleflu.org`?

**Comment by kairstenfay** [comment]
> I think the reference should still be `seattleflu.org`?

I thought so too, but looking at [past Slack history](https://seattle-flu-study.slack.com/archives/C018V0WGGJ0/p1598542694302200?thread_ts=1598478177.269200&cid=C018V0WGGJ0), I wrote a post at some point that suggested uw.edu or washington.edu. I can't recall why but figured there was a reason for it at the time. However, no one commented on it in the thread. I can easily change it.

**Comment by tsibley** [comment]
I think sticking with seattleflu.org makes most sense. The UW affiliation is indicated in the name already. Could compromise with seattleflu.org/uw.

**Review by joverlee521 — APPROVED** [review]

**Pull request merged**
