### PR TITLE
Pr 202 post merge review

### PR DESCRIPTION
**Pull request by kairstenfay**
Changes from a post-merge code review from #202.

### CODE REVIEW

**Comment by kairstenfay** [comment]
[id3c: post merge code review](https://trello.com/c/LIl76rfR/1018-id3c-post-merge-code-review)

**Review by kschwabefry — APPROVED** [review]

**Review by tsibley — APPROVED** [review]

**Comment by tsibley** [comment]
Thanks!

**Review by tsibley — COMMENTED** [review]
Upon further consideration in the related backoffice PR, I pushed another commit to this PR invalidating the fields property cache when `update_fields()` is called. Please give it a look and make sure it seems good to you before merge.

**Comment by kairstenfay** [comment]
> Upon further consideration in the related backoffice PR, I pushed another commit to this PR invalidating the fields property cache when `update_fields()` is called. Please give it a look and make sure it seems good to you before merge.

Oh, is that what the `@property` decorator does? That's neat. The changes look good to me. I'll wait to merge until the related backoffice PR is approved.

**Pull request merged**
