### PR TITLE
Support repeating REDCap

### PR DESCRIPTION
**Pull request by joverlee521**
See details in commit messages.

Needs to be deployed with changes in ID3C-customizations (https://github.com/seattleflu/id3c-customizations/pull/134)

### CODE REVIEW

**Comment by joverlee521** [comment]
[See what RedCAP records look like when a repeating instrument is used multiple times. How would we ingest that?](https://trello.com/c/z7eBYmud/743-see-what-redcap-records-look-like-when-a-repeating-instrument-is-used-multiple-times-how-would-we-ingest-that)

**Comment by kairstenfay** [comment]
> This looks really solid, Jover.
> 
> However, when I run `id3c redcap-det generate`, I get the following error:
> 
> ```
> TypeError: __init__() got an unexpected keyword argument 'required_instruments'
> ```

Hmm I think I posted this in the wrong PR. I'm going to post in the related id3c-customizations one.

**Review by tsibley — APPROVED** [review]
I was confused by this change in the second commit until I saw the third commit:

```diff
@@ -208,7 +201,7 @@ def command_for_project(name: str,                                                                                                                                         
                             instrument
                                 for instrument
                                 in required_instruments
-                                if not is_complete(instrument, redcap_record)                                                                                                                 
+                                if not is_complete(instrument, redcap_record_instances)                                                                                                       
                         }

                         if incomplete_instruments:
```

I expect that the modified version wouldn't work (right?), so it's a little odd to me to have the commits split up.

**Comment by joverlee521** [comment]
> I expect that the modified version wouldn't work (right?), so it's a little odd to me to have the commits split up.

Yeah, it wouldn't work. I can definitely squash the two commits together.

**Review by tsibley — APPROVED** [review]

**Pull request merged**
