### PR TITLE
Update clinical preprocess for SCH data

### PR DESCRIPTION
**Pull request by kairstenfay**
We are now receiving `census_tract` in the SCH clinical data :tada:.

In this latest clinical data pull from SCH, several column names were
also changed. The expected column names have been modified in this
commit.

### CODE REVIEW

**Comment by kairstenfay** [comment]
[Make changes for incoming SCH clinical data](https://trello.com/c/gALflipP/100-make-changes-for-incoming-sch-clinical-data)

**Comment by tsibley** [comment]
Trying this out on the new data, I ran into an unrelated issue, but perhaps one we should address on this branch too. I'll bring it up on Slack for discussion. In the meantime, I pushed a commit to improve debuggability of `update_sample`.

**Comment by kairstenfay** [comment]
Rebased, and yes let's discuss on Slack

**Comment by tsibley** [comment]
Code looks good, but let's wait to merge until we can test it with corrected data from Amanda.

**Comment by kairstenfay** [comment]
As addressed on Slack, Amanda says the most recent data are correct. Merging.

**Pull request merged**
